#!/bin/bash

installUbuntuSoftware() {
        nameCommand=$1
        namePackage=$2

        AVAILABLE=`which ${nameCommand}`
        if [ -z ${AVAILABLE} ]; then
          echo Installing $2
          sudo apt-get -y install ${namePackage}
          AVAILABLE=`which ${nameCommand}`
          if [ ! -x ${AVAILABLE} ]; then
            exit 1
          fi
        fi
}

usage() {
	printf "Usage: \n"
	printf "  -d <directory name> Directory containing the photo's \n"
	printf "  -a <artist name> Artist name that will be added to the EXIF info. \n"
	printf "  -c <copyright> Copyright that will be added to the EXIF info. \n"
	printf "  -t <tags> Tags that will be added as subject and keyword to the EXIF info. \n"
}

deleteFile() {
	if [ -f $1 ]
	then
		rm $1
	fi
}

count_extension () (
  ext="$1"
  dir="$2"
  any=false
  count=`find $dir -maxdepth 1 -type f -iname "*.$ext" |wc -l`
  echo $count
)

any_with_extension() {
  count=`count_extension $1 $2`
  if [[ $count == 0 ]]
    then
      any=false
    else
      any=true
  fi
  echo $any
}

rename() {

	COUNT=`ls -1 ${PHOTO_DIR}|wc -l`
	TAGS=`echo $TAGS | sed -e 's/[^\ ]*\ //'`
	TITLE=`echo $TAGS | sed -e 's/[^\ ]*\ //g'`

echo tags rename: $TAGS
echo title $TITLE

	echo "   Step 1: Temporary renaming pictures"
	SEQ=${#COUNT}
	exiftool -m -d %Y%m%d_%H%M%S_%%.${SEQ}c.%%e '-FileName<$CreateDate' ${PHOTO_DIR} > /dev/null

	#delete old files.txt
	deleteFile files.txt

	for foto in `find ${PHOTO_DIR} -maxdepth 1 -type f -iname "*.JPG" | sort`
	do
	  echo ${foto} >> files.txt
	done


	if [ -f files.txt ]
	then
	  echo "   Step 2: Renaming pictures to final name - "
	  echo "           format: <date>_"${TITLE}"_<sequence> "
	  exiftool -m -d %Y-%m-%d_${TITLE}_%%.${SEQ}nC.%%e '-FileName<$CreateDate' -@ files.txt > /dev/null

	  first=true

	  echo "   Step 3: Tagging "
	  for tag in ${TAGS}
	  do
	    tag=`echo $tag | sed -e 's/[-]/\ /g'`
	    if $first
	    then
	    echo "           Adding TAG: "$tag""
	      first=false
	      exiftool -m -artist="${ARTIST}" -copyright="${COPYRIGHT}" -overwrite_original -xmp-dc:Subject="${tag}" -keywords="${tag}" ${PHOTO_DIR} > /dev/null
	    else
	    echo "           Adding TAG: "$tag""
	      exiftool -m -overwrite_original -xmp-dc:Subject+="${tag}" -keywords+="${tag}" ${PHOTO_DIR} > /dev/null
	    fi
	  done
	  deleteFile files.txt
	fi
}


while getopts ":d:c:a:t:h" opt; do
  case $opt in
    d)
      export PHOTO_DIR=${OPTARG:-"."}
      ;;
    c)
      export COPYRIGHT=${OPTARG}
      ;;
    a)
      export ARTIST=${OPTARG}
      ;;
    t)
      export TAGS=${OPTARG:-${VERSION}}
      ;;
    h)
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# Check dialog is availble for using menus
echo tags: $TAGS
echo artist: $ARTIST
echo copyright: $COPYRIGHT
echo dir: $PHOTO_DIR

installUbuntuSoftware exiftool libimage-exiftool-perl
installUbuntuSoftware jhead jhead

if [[ `any_with_extension JPG $PHOTO_DIR` && ! -z ${TAGS} ]]
then
  rename
  jhead -ft -c -q $PHOTO_DIR/*.JPG > /dev/null
else
  usage
fi
